// <auto-generated />
using Ispit.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ispit.Api.Migrations.ShoppingItem
{
    [DbContext(typeof(ShoppingItemContext))]
    partial class ShoppingItemContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ispit.Api.Models.ShoppingItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("ShoppingItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Manufacturer = "TechCorp",
                            Name = "Laptop",
                            Price = 999.99m
                        },
                        new
                        {
                            Id = 2,
                            Manufacturer = "Gizmo Inc.",
                            Name = "Smartphone",
                            Price = 499.99m
                        },
                        new
                        {
                            Id = 3,
                            Manufacturer = "AudioPro",
                            Name = "Headphones",
                            Price = 89.99m
                        },
                        new
                        {
                            Id = 4,
                            Manufacturer = "KeyMaster",
                            Name = "Keyboard",
                            Price = 29.99m
                        },
                        new
                        {
                            Id = 5,
                            Manufacturer = "Clicker",
                            Name = "Mouse",
                            Price = 19.99m
                        },
                        new
                        {
                            Id = 6,
                            Manufacturer = "VisionTech",
                            Name = "Monitor",
                            Price = 149.99m
                        },
                        new
                        {
                            Id = 7,
                            Manufacturer = "PrintMaster",
                            Name = "Printer",
                            Price = 79.99m
                        },
                        new
                        {
                            Id = 8,
                            Manufacturer = "CamCo",
                            Name = "Webcam",
                            Price = 59.99m
                        },
                        new
                        {
                            Id = 9,
                            Manufacturer = "DataStick",
                            Name = "USB Drive",
                            Price = 12.99m
                        },
                        new
                        {
                            Id = 10,
                            Manufacturer = "StoragePlus",
                            Name = "External Hard Drive",
                            Price = 129.99m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
